// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/consumer_rebalance/consumer_rebalance.proto

package consumer_rebalance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RebalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	PartitionIDs  []int32                `protobuf:"varint,2,rep,packed,name=PartitionIDs,proto3" json:"PartitionIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceRequest) Reset() {
	*x = RebalanceRequest{}
	mi := &file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceRequest) ProtoMessage() {}

func (x *RebalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceRequest.ProtoReflect.Descriptor instead.
func (*RebalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_consumer_rebalance_consumer_rebalance_proto_rawDescGZIP(), []int{0}
}

func (x *RebalanceRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *RebalanceRequest) GetPartitionIDs() []int32 {
	if x != nil {
		return x.PartitionIDs
	}
	return nil
}

type RebalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceResponse) Reset() {
	*x = RebalanceResponse{}
	mi := &file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceResponse) ProtoMessage() {}

func (x *RebalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceResponse.ProtoReflect.Descriptor instead.
func (*RebalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_consumer_rebalance_consumer_rebalance_proto_rawDescGZIP(), []int{1}
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	PartitionIDs  []int32                `protobuf:"varint,2,rep,packed,name=PartitionIDs,proto3" json:"PartitionIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_api_consumer_rebalance_consumer_rebalance_proto_rawDescGZIP(), []int{2}
}

func (x *CommitRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *CommitRequest) GetPartitionIDs() []int32 {
	if x != nil {
		return x.PartitionIDs
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_api_consumer_rebalance_consumer_rebalance_proto_rawDescGZIP(), []int{3}
}

var File_api_consumer_rebalance_consumer_rebalance_proto protoreflect.FileDescriptor

const file_api_consumer_rebalance_consumer_rebalance_proto_rawDesc = "" +
	"\n" +
	"/api/consumer_rebalance/consumer_rebalance.proto\x12\x12consumer_rebalance\"N\n" +
	"\x10RebalanceRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\x12\"\n" +
	"\fPartitionIDs\x18\x02 \x03(\x05R\fPartitionIDs\"\x13\n" +
	"\x11RebalanceResponse\"K\n" +
	"\rCommitRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\x12\"\n" +
	"\fPartitionIDs\x18\x02 \x03(\x05R\fPartitionIDs\"\x10\n" +
	"\x0eCommitResponse2\xc3\x01\n" +
	"\x12consumer_rebalance\x12Z\n" +
	"\tRebalance\x12$.consumer_rebalance.RebalanceRequest\x1a%.consumer_rebalance.RebalanceResponse\"\x00\x12Q\n" +
	"\x06Commit\x12!.consumer_rebalance.CommitRequest\x1a\".consumer_rebalance.CommitResponse\"\x00B\x18Z\x16api/consumer_rebalanceb\x06proto3"

var (
	file_api_consumer_rebalance_consumer_rebalance_proto_rawDescOnce sync.Once
	file_api_consumer_rebalance_consumer_rebalance_proto_rawDescData []byte
)

func file_api_consumer_rebalance_consumer_rebalance_proto_rawDescGZIP() []byte {
	file_api_consumer_rebalance_consumer_rebalance_proto_rawDescOnce.Do(func() {
		file_api_consumer_rebalance_consumer_rebalance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_consumer_rebalance_consumer_rebalance_proto_rawDesc), len(file_api_consumer_rebalance_consumer_rebalance_proto_rawDesc)))
	})
	return file_api_consumer_rebalance_consumer_rebalance_proto_rawDescData
}

var file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_consumer_rebalance_consumer_rebalance_proto_goTypes = []any{
	(*RebalanceRequest)(nil),  // 0: consumer_rebalance.RebalanceRequest
	(*RebalanceResponse)(nil), // 1: consumer_rebalance.RebalanceResponse
	(*CommitRequest)(nil),     // 2: consumer_rebalance.CommitRequest
	(*CommitResponse)(nil),    // 3: consumer_rebalance.CommitResponse
}
var file_api_consumer_rebalance_consumer_rebalance_proto_depIdxs = []int32{
	0, // 0: consumer_rebalance.consumer_rebalance.Rebalance:input_type -> consumer_rebalance.RebalanceRequest
	2, // 1: consumer_rebalance.consumer_rebalance.Commit:input_type -> consumer_rebalance.CommitRequest
	1, // 2: consumer_rebalance.consumer_rebalance.Rebalance:output_type -> consumer_rebalance.RebalanceResponse
	3, // 3: consumer_rebalance.consumer_rebalance.Commit:output_type -> consumer_rebalance.CommitResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_consumer_rebalance_consumer_rebalance_proto_init() }
func file_api_consumer_rebalance_consumer_rebalance_proto_init() {
	if File_api_consumer_rebalance_consumer_rebalance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_consumer_rebalance_consumer_rebalance_proto_rawDesc), len(file_api_consumer_rebalance_consumer_rebalance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_consumer_rebalance_consumer_rebalance_proto_goTypes,
		DependencyIndexes: file_api_consumer_rebalance_consumer_rebalance_proto_depIdxs,
		MessageInfos:      file_api_consumer_rebalance_consumer_rebalance_proto_msgTypes,
	}.Build()
	File_api_consumer_rebalance_consumer_rebalance_proto = out.File
	file_api_consumer_rebalance_consumer_rebalance_proto_goTypes = nil
	file_api_consumer_rebalance_consumer_rebalance_proto_depIdxs = nil
}
