// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: api/storage_info/storage_info.proto

package storage_info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *uint64                `protobuf:"varint,1,opt,name=Index,proto3,oneof" json:"Index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3,oneof" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_storage_info_storage_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_info_storage_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_storage_info_storage_info_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProducerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            *uint64                `protobuf:"varint,1,opt,name=ID,proto3,oneof" json:"ID,omitempty"`
	Sequence      *uint64                `protobuf:"varint,2,opt,name=Sequence,proto3,oneof" json:"Sequence,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,3,opt,name=Timestamp,proto3,oneof" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerID) Reset() {
	*x = ProducerID{}
	mi := &file_api_storage_info_storage_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerID) ProtoMessage() {}

func (x *ProducerID) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_info_storage_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerID.ProtoReflect.Descriptor instead.
func (*ProducerID) Descriptor() ([]byte, []int) {
	return file_api_storage_info_storage_info_proto_rawDescGZIP(), []int{1}
}

func (x *ProducerID) GetID() uint64 {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return 0
}

func (x *ProducerID) GetSequence() uint64 {
	if x != nil && x.Sequence != nil {
		return *x.Sequence
	}
	return 0
}

func (x *ProducerID) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type ConsumerCommitIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       *string                `protobuf:"bytes,1,opt,name=GroupID,proto3,oneof" json:"GroupID,omitempty"`
	CommitIndex   *uint64                `protobuf:"varint,2,opt,name=CommitIndex,proto3,oneof" json:"CommitIndex,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,3,opt,name=Timestamp,proto3,oneof" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerCommitIndex) Reset() {
	*x = ConsumerCommitIndex{}
	mi := &file_api_storage_info_storage_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerCommitIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerCommitIndex) ProtoMessage() {}

func (x *ConsumerCommitIndex) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_info_storage_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerCommitIndex.ProtoReflect.Descriptor instead.
func (*ConsumerCommitIndex) Descriptor() ([]byte, []int) {
	return file_api_storage_info_storage_info_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumerCommitIndex) GetGroupID() string {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return ""
}

func (x *ConsumerCommitIndex) GetCommitIndex() uint64 {
	if x != nil && x.CommitIndex != nil {
		return *x.CommitIndex
	}
	return 0
}

func (x *ConsumerCommitIndex) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type ReplicativeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          [][]byte               `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicativeData) Reset() {
	*x = ReplicativeData{}
	mi := &file_api_storage_info_storage_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicativeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicativeData) ProtoMessage() {}

func (x *ReplicativeData) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_info_storage_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicativeData.ProtoReflect.Descriptor instead.
func (*ReplicativeData) Descriptor() ([]byte, []int) {
	return file_api_storage_info_storage_info_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicativeData) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_storage_info_storage_info_proto protoreflect.FileDescriptor

var file_api_storage_info_storage_info_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x4f, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a,
	0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x05,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x87, 0x01, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x13, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48,
	0x00, 0x52, 0x02, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x53, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x08, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02, 0x52, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03,
	0x5f, 0x49, 0x44, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xa8,
	0x01, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x0b, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48,
	0x02, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x25, 0x0a, 0x0f, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x12, 0x5a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_storage_info_storage_info_proto_rawDescOnce sync.Once
	file_api_storage_info_storage_info_proto_rawDescData []byte
)

func file_api_storage_info_storage_info_proto_rawDescGZIP() []byte {
	file_api_storage_info_storage_info_proto_rawDescOnce.Do(func() {
		file_api_storage_info_storage_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_storage_info_storage_info_proto_rawDesc), len(file_api_storage_info_storage_info_proto_rawDesc)))
	})
	return file_api_storage_info_storage_info_proto_rawDescData
}

var file_api_storage_info_storage_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_storage_info_storage_info_proto_goTypes = []any{
	(*Record)(nil),              // 0: storage_info.Record
	(*ProducerID)(nil),          // 1: storage_info.ProducerID
	(*ConsumerCommitIndex)(nil), // 2: storage_info.ConsumerCommitIndex
	(*ReplicativeData)(nil),     // 3: storage_info.ReplicativeData
}
var file_api_storage_info_storage_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_storage_info_storage_info_proto_init() }
func file_api_storage_info_storage_info_proto_init() {
	if File_api_storage_info_storage_info_proto != nil {
		return
	}
	file_api_storage_info_storage_info_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_storage_info_storage_info_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_storage_info_storage_info_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_storage_info_storage_info_proto_rawDesc), len(file_api_storage_info_storage_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_storage_info_storage_info_proto_goTypes,
		DependencyIndexes: file_api_storage_info_storage_info_proto_depIdxs,
		MessageInfos:      file_api_storage_info_storage_info_proto_msgTypes,
	}.Build()
	File_api_storage_info_storage_info_proto = out.File
	file_api_storage_info_storage_info_proto_goTypes = nil
	file_api_storage_info_storage_info_proto_depIdxs = nil
}
