// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/broker_rpc/broker_rpc.proto

package broker_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetCode int32

const (
	RetCode_SUCCESS   RetCode = 0
	RetCode_NotLeader RetCode = 1
	RetCode_TimeOut   RetCode = 2
	RetCode_ErrOther  RetCode = 3
)

// Enum value maps for RetCode.
var (
	RetCode_name = map[int32]string{
		0: "SUCCESS",
		1: "NotLeader",
		2: "TimeOut",
		3: "ErrOther",
	}
	RetCode_value = map[string]int32{
		"SUCCESS":   0,
		"NotLeader": 1,
		"TimeOut":   2,
		"ErrOther":  3,
	}
)

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}

func (x RetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_broker_rpc_broker_rpc_proto_enumTypes[0].Descriptor()
}

func (RetCode) Type() protoreflect.EnumType {
	return &file_api_broker_rpc_broker_rpc_proto_enumTypes[0]
}

func (x RetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetCode.Descriptor instead.
func (RetCode) EnumDescriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{0}
}

type PushMessagesRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Topics        []*PushMessagesRequest_Topic `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessagesRequest) Reset() {
	*x = PushMessagesRequest{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessagesRequest) ProtoMessage() {}

func (x *PushMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessagesRequest.ProtoReflect.Descriptor instead.
func (*PushMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *PushMessagesRequest) GetTopics() []*PushMessagesRequest_Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type PushMessagesResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Topics        []*PushMessagesResponse_TopicResponses `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessagesResponse) Reset() {
	*x = PushMessagesResponse{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessagesResponse) ProtoMessage() {}

func (x *PushMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessagesResponse.ProtoReflect.Descriptor instead.
func (*PushMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *PushMessagesResponse) GetTopics() []*PushMessagesResponse_TopicResponses {
	if x != nil {
		return x.Topics
	}
	return nil
}

type PullMessagesRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Topics        []*PullMessagesRequest_Topic `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesRequest) Reset() {
	*x = PullMessagesRequest{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesRequest) ProtoMessage() {}

func (x *PullMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesRequest.ProtoReflect.Descriptor instead.
func (*PullMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *PullMessagesRequest) GetTopics() []*PullMessagesRequest_Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type PullMessagesResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Topics        []*PullMessagesResponse_TopicResponses `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesResponse) Reset() {
	*x = PullMessagesResponse{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesResponse) ProtoMessage() {}

func (x *PullMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesResponse.ProtoReflect.Descriptor instead.
func (*PullMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *PullMessagesResponse) GetTopics() []*PullMessagesResponse_TopicResponses {
	if x != nil {
		return x.Topics
	}
	return nil
}

type CommitIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup *string                `protobuf:"bytes,1,opt,name=ConsumerGroup,proto3,oneof" json:"ConsumerGroup,omitempty"`
	TopicName     *string                `protobuf:"bytes,2,opt,name=TopicName,proto3,oneof" json:"TopicName,omitempty"`
	PartitionID   *int32                 `protobuf:"varint,3,opt,name=PartitionID,proto3,oneof" json:"PartitionID,omitempty"`
	CommitIndex   *uint64                `protobuf:"varint,4,opt,name=CommitIndex,proto3,oneof" json:"CommitIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitIndexRequest) Reset() {
	*x = CommitIndexRequest{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitIndexRequest) ProtoMessage() {}

func (x *CommitIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitIndexRequest.ProtoReflect.Descriptor instead.
func (*CommitIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *CommitIndexRequest) GetConsumerGroup() string {
	if x != nil && x.ConsumerGroup != nil {
		return *x.ConsumerGroup
	}
	return ""
}

func (x *CommitIndexRequest) GetTopicName() string {
	if x != nil && x.TopicName != nil {
		return *x.TopicName
	}
	return ""
}

func (x *CommitIndexRequest) GetPartitionID() int32 {
	if x != nil && x.PartitionID != nil {
		return *x.PartitionID
	}
	return 0
}

func (x *CommitIndexRequest) GetCommitIndex() uint64 {
	if x != nil && x.CommitIndex != nil {
		return *x.CommitIndex
	}
	return 0
}

type CommitIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *RetCode               `protobuf:"varint,1,opt,name=Ret,proto3,enum=broker_rpc.RetCode,oneof" json:"Ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitIndexResponse) Reset() {
	*x = CommitIndexResponse{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitIndexResponse) ProtoMessage() {}

func (x *CommitIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitIndexResponse.ProtoReflect.Descriptor instead.
func (*CommitIndexResponse) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *CommitIndexResponse) GetRet() RetCode {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return RetCode_SUCCESS
}

type GetCommitIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup *string                `protobuf:"bytes,1,opt,name=ConsumerGroup,proto3,oneof" json:"ConsumerGroup,omitempty"`
	TopicName     *string                `protobuf:"bytes,2,opt,name=TopicName,proto3,oneof" json:"TopicName,omitempty"`
	PartitionID   *int32                 `protobuf:"varint,3,opt,name=PartitionID,proto3,oneof" json:"PartitionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitIndexRequest) Reset() {
	*x = GetCommitIndexRequest{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitIndexRequest) ProtoMessage() {}

func (x *GetCommitIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitIndexRequest.ProtoReflect.Descriptor instead.
func (*GetCommitIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommitIndexRequest) GetConsumerGroup() string {
	if x != nil && x.ConsumerGroup != nil {
		return *x.ConsumerGroup
	}
	return ""
}

func (x *GetCommitIndexRequest) GetTopicName() string {
	if x != nil && x.TopicName != nil {
		return *x.TopicName
	}
	return ""
}

func (x *GetCommitIndexRequest) GetPartitionID() int32 {
	if x != nil && x.PartitionID != nil {
		return *x.PartitionID
	}
	return 0
}

type GetCommitIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *RetCode               `protobuf:"varint,1,opt,name=Ret,proto3,enum=broker_rpc.RetCode,oneof" json:"Ret,omitempty"`
	CommitIndex   *uint64                `protobuf:"varint,2,opt,name=CommitIndex,proto3,oneof" json:"CommitIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitIndexResponse) Reset() {
	*x = GetCommitIndexResponse{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitIndexResponse) ProtoMessage() {}

func (x *GetCommitIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitIndexResponse.ProtoReflect.Descriptor instead.
func (*GetCommitIndexResponse) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommitIndexResponse) GetRet() RetCode {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return RetCode_SUCCESS
}

func (x *GetCommitIndexResponse) GetCommitIndex() uint64 {
	if x != nil && x.CommitIndex != nil {
		return *x.CommitIndex
	}
	return 0
}

type InitProducerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     *string                `protobuf:"bytes,1,opt,name=TopicName,proto3,oneof" json:"TopicName,omitempty"`
	PartitionID   *int32                 `protobuf:"varint,2,opt,name=PartitionID,proto3,oneof" json:"PartitionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitProducerIDRequest) Reset() {
	*x = InitProducerIDRequest{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitProducerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitProducerIDRequest) ProtoMessage() {}

func (x *InitProducerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitProducerIDRequest.ProtoReflect.Descriptor instead.
func (*InitProducerIDRequest) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *InitProducerIDRequest) GetTopicName() string {
	if x != nil && x.TopicName != nil {
		return *x.TopicName
	}
	return ""
}

func (x *InitProducerIDRequest) GetPartitionID() int32 {
	if x != nil && x.PartitionID != nil {
		return *x.PartitionID
	}
	return 0
}

type InitProducerIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *RetCode               `protobuf:"varint,1,opt,name=Ret,proto3,enum=broker_rpc.RetCode,oneof" json:"Ret,omitempty"`
	ProducerID    *uint64                `protobuf:"varint,2,opt,name=ProducerID,proto3,oneof" json:"ProducerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitProducerIDResponse) Reset() {
	*x = InitProducerIDResponse{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitProducerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitProducerIDResponse) ProtoMessage() {}

func (x *InitProducerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitProducerIDResponse.ProtoReflect.Descriptor instead.
func (*InitProducerIDResponse) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *InitProducerIDResponse) GetRet() RetCode {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return RetCode_SUCCESS
}

func (x *InitProducerIDResponse) GetProducerID() uint64 {
	if x != nil && x.ProducerID != nil {
		return *x.ProducerID
	}
	return 0
}

type PushMessagesRequest_Topic struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	TopicName     *string                                `protobuf:"bytes,1,opt,name=TopicName,proto3,oneof" json:"TopicName,omitempty"`
	Partitions    []*PushMessagesRequest_Topic_Partition `protobuf:"bytes,2,rep,name=Partitions,proto3" json:"Partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessagesRequest_Topic) Reset() {
	*x = PushMessagesRequest_Topic{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessagesRequest_Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessagesRequest_Topic) ProtoMessage() {}

func (x *PushMessagesRequest_Topic) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessagesRequest_Topic.ProtoReflect.Descriptor instead.
func (*PushMessagesRequest_Topic) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PushMessagesRequest_Topic) GetTopicName() string {
	if x != nil && x.TopicName != nil {
		return *x.TopicName
	}
	return ""
}

func (x *PushMessagesRequest_Topic) GetPartitions() []*PushMessagesRequest_Topic_Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PushMessagesRequest_Topic_Partition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartitionID    *int32                 `protobuf:"varint,1,opt,name=PartitionID,proto3,oneof" json:"PartitionID,omitempty"`
	Datas          [][]byte               `protobuf:"bytes,2,rep,name=Datas,proto3" json:"Datas,omitempty"`
	ProducerID     *uint64                `protobuf:"varint,3,opt,name=ProducerID,proto3,oneof" json:"ProducerID,omitempty"`
	SequenceNumber *uint64                `protobuf:"varint,4,opt,name=SequenceNumber,proto3,oneof" json:"SequenceNumber,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushMessagesRequest_Topic_Partition) Reset() {
	*x = PushMessagesRequest_Topic_Partition{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessagesRequest_Topic_Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessagesRequest_Topic_Partition) ProtoMessage() {}

func (x *PushMessagesRequest_Topic_Partition) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessagesRequest_Topic_Partition.ProtoReflect.Descriptor instead.
func (*PushMessagesRequest_Topic_Partition) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PushMessagesRequest_Topic_Partition) GetPartitionID() int32 {
	if x != nil && x.PartitionID != nil {
		return *x.PartitionID
	}
	return 0
}

func (x *PushMessagesRequest_Topic_Partition) GetDatas() [][]byte {
	if x != nil {
		return x.Datas
	}
	return nil
}

func (x *PushMessagesRequest_Topic_Partition) GetProducerID() uint64 {
	if x != nil && x.ProducerID != nil {
		return *x.ProducerID
	}
	return 0
}

func (x *PushMessagesRequest_Topic_Partition) GetSequenceNumber() uint64 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

type PushMessagesResponse_TopicResponses struct {
	state         protoimpl.MessageState                                    `protogen:"open.v1"`
	TopicName     *string                                                   `protobuf:"bytes,1,opt,name=TopicName,proto3,oneof" json:"TopicName,omitempty"`
	Partitions    []*PushMessagesResponse_TopicResponses_PartitionResponses `protobuf:"bytes,2,rep,name=Partitions,proto3" json:"Partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessagesResponse_TopicResponses) Reset() {
	*x = PushMessagesResponse_TopicResponses{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessagesResponse_TopicResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessagesResponse_TopicResponses) ProtoMessage() {}

func (x *PushMessagesResponse_TopicResponses) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessagesResponse_TopicResponses.ProtoReflect.Descriptor instead.
func (*PushMessagesResponse_TopicResponses) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PushMessagesResponse_TopicResponses) GetTopicName() string {
	if x != nil && x.TopicName != nil {
		return *x.TopicName
	}
	return ""
}

func (x *PushMessagesResponse_TopicResponses) GetPartitions() []*PushMessagesResponse_TopicResponses_PartitionResponses {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PushMessagesResponse_TopicResponses_PartitionResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionID   *int32                 `protobuf:"varint,1,opt,name=PartitionID,proto3,oneof" json:"PartitionID,omitempty"`
	Ret           *RetCode               `protobuf:"varint,2,opt,name=Ret,proto3,enum=broker_rpc.RetCode,oneof" json:"Ret,omitempty"`
	StartIndex    *uint64                `protobuf:"varint,3,opt,name=StartIndex,proto3,oneof" json:"StartIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessagesResponse_TopicResponses_PartitionResponses) Reset() {
	*x = PushMessagesResponse_TopicResponses_PartitionResponses{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessagesResponse_TopicResponses_PartitionResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessagesResponse_TopicResponses_PartitionResponses) ProtoMessage() {}

func (x *PushMessagesResponse_TopicResponses_PartitionResponses) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessagesResponse_TopicResponses_PartitionResponses.ProtoReflect.Descriptor instead.
func (*PushMessagesResponse_TopicResponses_PartitionResponses) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *PushMessagesResponse_TopicResponses_PartitionResponses) GetPartitionID() int32 {
	if x != nil && x.PartitionID != nil {
		return *x.PartitionID
	}
	return 0
}

func (x *PushMessagesResponse_TopicResponses_PartitionResponses) GetRet() RetCode {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return RetCode_SUCCESS
}

func (x *PushMessagesResponse_TopicResponses_PartitionResponses) GetStartIndex() uint64 {
	if x != nil && x.StartIndex != nil {
		return *x.StartIndex
	}
	return 0
}

type PullMessagesRequest_Topic struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	TopicName     *string                                `protobuf:"bytes,1,opt,name=TopicName,proto3,oneof" json:"TopicName,omitempty"`
	Partitions    []*PullMessagesRequest_Topic_Partition `protobuf:"bytes,2,rep,name=Partitions,proto3" json:"Partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesRequest_Topic) Reset() {
	*x = PullMessagesRequest_Topic{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesRequest_Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesRequest_Topic) ProtoMessage() {}

func (x *PullMessagesRequest_Topic) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesRequest_Topic.ProtoReflect.Descriptor instead.
func (*PullMessagesRequest_Topic) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PullMessagesRequest_Topic) GetTopicName() string {
	if x != nil && x.TopicName != nil {
		return *x.TopicName
	}
	return ""
}

func (x *PullMessagesRequest_Topic) GetPartitions() []*PullMessagesRequest_Topic_Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PullMessagesRequest_Topic_Partition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionID   *int32                 `protobuf:"varint,1,opt,name=PartitionID,proto3,oneof" json:"PartitionID,omitempty"`
	FetchIndex    *uint64                `protobuf:"varint,2,opt,name=FetchIndex,proto3,oneof" json:"FetchIndex,omitempty"`
	MaxBytes      *uint32                `protobuf:"varint,3,opt,name=MaxBytes,proto3,oneof" json:"MaxBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesRequest_Topic_Partition) Reset() {
	*x = PullMessagesRequest_Topic_Partition{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesRequest_Topic_Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesRequest_Topic_Partition) ProtoMessage() {}

func (x *PullMessagesRequest_Topic_Partition) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesRequest_Topic_Partition.ProtoReflect.Descriptor instead.
func (*PullMessagesRequest_Topic_Partition) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *PullMessagesRequest_Topic_Partition) GetPartitionID() int32 {
	if x != nil && x.PartitionID != nil {
		return *x.PartitionID
	}
	return 0
}

func (x *PullMessagesRequest_Topic_Partition) GetFetchIndex() uint64 {
	if x != nil && x.FetchIndex != nil {
		return *x.FetchIndex
	}
	return 0
}

func (x *PullMessagesRequest_Topic_Partition) GetMaxBytes() uint32 {
	if x != nil && x.MaxBytes != nil {
		return *x.MaxBytes
	}
	return 0
}

type PullMessagesResponse_TopicResponses struct {
	state         protoimpl.MessageState                                    `protogen:"open.v1"`
	TopicName     *string                                                   `protobuf:"bytes,1,opt,name=TopicName,proto3,oneof" json:"TopicName,omitempty"`
	Partitions    []*PullMessagesResponse_TopicResponses_PartitionResponses `protobuf:"bytes,2,rep,name=Partitions,proto3" json:"Partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesResponse_TopicResponses) Reset() {
	*x = PullMessagesResponse_TopicResponses{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesResponse_TopicResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesResponse_TopicResponses) ProtoMessage() {}

func (x *PullMessagesResponse_TopicResponses) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesResponse_TopicResponses.ProtoReflect.Descriptor instead.
func (*PullMessagesResponse_TopicResponses) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{3, 0}
}

func (x *PullMessagesResponse_TopicResponses) GetTopicName() string {
	if x != nil && x.TopicName != nil {
		return *x.TopicName
	}
	return ""
}

func (x *PullMessagesResponse_TopicResponses) GetPartitions() []*PullMessagesResponse_TopicResponses_PartitionResponses {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PullMessagesResponse_TopicResponses_PartitionResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionID   *int32                 `protobuf:"varint,1,opt,name=PartitionID,proto3,oneof" json:"PartitionID,omitempty"`
	Ret           *RetCode               `protobuf:"varint,2,opt,name=Ret,proto3,enum=broker_rpc.RetCode,oneof" json:"Ret,omitempty"`
	Datas         [][]byte               `protobuf:"bytes,3,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesResponse_TopicResponses_PartitionResponses) Reset() {
	*x = PullMessagesResponse_TopicResponses_PartitionResponses{}
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesResponse_TopicResponses_PartitionResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesResponse_TopicResponses_PartitionResponses) ProtoMessage() {}

func (x *PullMessagesResponse_TopicResponses_PartitionResponses) ProtoReflect() protoreflect.Message {
	mi := &file_api_broker_rpc_broker_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesResponse_TopicResponses_PartitionResponses.ProtoReflect.Descriptor instead.
func (*PullMessagesResponse_TopicResponses_PartitionResponses) Descriptor() ([]byte, []int) {
	return file_api_broker_rpc_broker_rpc_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *PullMessagesResponse_TopicResponses_PartitionResponses) GetPartitionID() int32 {
	if x != nil && x.PartitionID != nil {
		return *x.PartitionID
	}
	return 0
}

func (x *PullMessagesResponse_TopicResponses_PartitionResponses) GetRet() RetCode {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return RetCode_SUCCESS
}

func (x *PullMessagesResponse_TopicResponses_PartitionResponses) GetDatas() [][]byte {
	if x != nil {
		return x.Datas
	}
	return nil
}

var File_api_broker_rpc_broker_rpc_proto protoreflect.FileDescriptor

const file_api_broker_rpc_broker_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/broker_rpc/broker_rpc.proto\x12\n" +
	"broker_rpc\"\xaf\x03\n" +
	"\x13PushMessagesRequest\x12=\n" +
	"\x06Topics\x18\x01 \x03(\v2%.broker_rpc.PushMessagesRequest.TopicR\x06Topics\x1a\xd8\x02\n" +
	"\x05Topic\x12!\n" +
	"\tTopicName\x18\x01 \x01(\tH\x00R\tTopicName\x88\x01\x01\x12O\n" +
	"\n" +
	"Partitions\x18\x02 \x03(\v2/.broker_rpc.PushMessagesRequest.Topic.PartitionR\n" +
	"Partitions\x1a\xcc\x01\n" +
	"\tPartition\x12%\n" +
	"\vPartitionID\x18\x01 \x01(\x05H\x00R\vPartitionID\x88\x01\x01\x12\x14\n" +
	"\x05Datas\x18\x02 \x03(\fR\x05Datas\x12#\n" +
	"\n" +
	"ProducerID\x18\x03 \x01(\x04H\x01R\n" +
	"ProducerID\x88\x01\x01\x12+\n" +
	"\x0eSequenceNumber\x18\x04 \x01(\x04H\x02R\x0eSequenceNumber\x88\x01\x01B\x0e\n" +
	"\f_PartitionIDB\r\n" +
	"\v_ProducerIDB\x11\n" +
	"\x0f_SequenceNumberB\f\n" +
	"\n" +
	"_TopicName\"\xbd\x03\n" +
	"\x14PushMessagesResponse\x12G\n" +
	"\x06Topics\x18\x01 \x03(\v2/.broker_rpc.PushMessagesResponse.TopicResponsesR\x06Topics\x1a\xdb\x02\n" +
	"\x0eTopicResponses\x12!\n" +
	"\tTopicName\x18\x01 \x01(\tH\x00R\tTopicName\x88\x01\x01\x12b\n" +
	"\n" +
	"Partitions\x18\x02 \x03(\v2B.broker_rpc.PushMessagesResponse.TopicResponses.PartitionResponsesR\n" +
	"Partitions\x1a\xb3\x01\n" +
	"\x12PartitionResponses\x12%\n" +
	"\vPartitionID\x18\x01 \x01(\x05H\x00R\vPartitionID\x88\x01\x01\x12*\n" +
	"\x03Ret\x18\x02 \x01(\x0e2\x13.broker_rpc.RetCodeH\x01R\x03Ret\x88\x01\x01\x12#\n" +
	"\n" +
	"StartIndex\x18\x03 \x01(\x04H\x02R\n" +
	"StartIndex\x88\x01\x01B\x0e\n" +
	"\f_PartitionIDB\x06\n" +
	"\x04_RetB\r\n" +
	"\v_StartIndexB\f\n" +
	"\n" +
	"_TopicName\"\x87\x03\n" +
	"\x13PullMessagesRequest\x12=\n" +
	"\x06Topics\x18\x01 \x03(\v2%.broker_rpc.PullMessagesRequest.TopicR\x06Topics\x1a\xb0\x02\n" +
	"\x05Topic\x12!\n" +
	"\tTopicName\x18\x01 \x01(\tH\x00R\tTopicName\x88\x01\x01\x12O\n" +
	"\n" +
	"Partitions\x18\x02 \x03(\v2/.broker_rpc.PullMessagesRequest.Topic.PartitionR\n" +
	"Partitions\x1a\xa4\x01\n" +
	"\tPartition\x12%\n" +
	"\vPartitionID\x18\x01 \x01(\x05H\x00R\vPartitionID\x88\x01\x01\x12#\n" +
	"\n" +
	"FetchIndex\x18\x02 \x01(\x04H\x01R\n" +
	"FetchIndex\x88\x01\x01\x12\x1f\n" +
	"\bMaxBytes\x18\x03 \x01(\rH\x02R\bMaxBytes\x88\x01\x01B\x0e\n" +
	"\f_PartitionIDB\r\n" +
	"\v_FetchIndexB\v\n" +
	"\t_MaxBytesB\f\n" +
	"\n" +
	"_TopicName\"\x9f\x03\n" +
	"\x14PullMessagesResponse\x12G\n" +
	"\x06Topics\x18\x01 \x03(\v2/.broker_rpc.PullMessagesResponse.TopicResponsesR\x06Topics\x1a\xbd\x02\n" +
	"\x0eTopicResponses\x12!\n" +
	"\tTopicName\x18\x01 \x01(\tH\x00R\tTopicName\x88\x01\x01\x12b\n" +
	"\n" +
	"Partitions\x18\x02 \x03(\v2B.broker_rpc.PullMessagesResponse.TopicResponses.PartitionResponsesR\n" +
	"Partitions\x1a\x95\x01\n" +
	"\x12PartitionResponses\x12%\n" +
	"\vPartitionID\x18\x01 \x01(\x05H\x00R\vPartitionID\x88\x01\x01\x12*\n" +
	"\x03Ret\x18\x02 \x01(\x0e2\x13.broker_rpc.RetCodeH\x01R\x03Ret\x88\x01\x01\x12\x14\n" +
	"\x05Datas\x18\x03 \x03(\fR\x05DatasB\x0e\n" +
	"\f_PartitionIDB\x06\n" +
	"\x04_RetB\f\n" +
	"\n" +
	"_TopicName\"\xf0\x01\n" +
	"\x12CommitIndexRequest\x12)\n" +
	"\rConsumerGroup\x18\x01 \x01(\tH\x00R\rConsumerGroup\x88\x01\x01\x12!\n" +
	"\tTopicName\x18\x02 \x01(\tH\x01R\tTopicName\x88\x01\x01\x12%\n" +
	"\vPartitionID\x18\x03 \x01(\x05H\x02R\vPartitionID\x88\x01\x01\x12%\n" +
	"\vCommitIndex\x18\x04 \x01(\x04H\x03R\vCommitIndex\x88\x01\x01B\x10\n" +
	"\x0e_ConsumerGroupB\f\n" +
	"\n" +
	"_TopicNameB\x0e\n" +
	"\f_PartitionIDB\x0e\n" +
	"\f_CommitIndex\"I\n" +
	"\x13CommitIndexResponse\x12*\n" +
	"\x03Ret\x18\x01 \x01(\x0e2\x13.broker_rpc.RetCodeH\x00R\x03Ret\x88\x01\x01B\x06\n" +
	"\x04_Ret\"\xbc\x01\n" +
	"\x15GetCommitIndexRequest\x12)\n" +
	"\rConsumerGroup\x18\x01 \x01(\tH\x00R\rConsumerGroup\x88\x01\x01\x12!\n" +
	"\tTopicName\x18\x02 \x01(\tH\x01R\tTopicName\x88\x01\x01\x12%\n" +
	"\vPartitionID\x18\x03 \x01(\x05H\x02R\vPartitionID\x88\x01\x01B\x10\n" +
	"\x0e_ConsumerGroupB\f\n" +
	"\n" +
	"_TopicNameB\x0e\n" +
	"\f_PartitionID\"\x83\x01\n" +
	"\x16GetCommitIndexResponse\x12*\n" +
	"\x03Ret\x18\x01 \x01(\x0e2\x13.broker_rpc.RetCodeH\x00R\x03Ret\x88\x01\x01\x12%\n" +
	"\vCommitIndex\x18\x02 \x01(\x04H\x01R\vCommitIndex\x88\x01\x01B\x06\n" +
	"\x04_RetB\x0e\n" +
	"\f_CommitIndex\"\x7f\n" +
	"\x15InitProducerIDRequest\x12!\n" +
	"\tTopicName\x18\x01 \x01(\tH\x00R\tTopicName\x88\x01\x01\x12%\n" +
	"\vPartitionID\x18\x02 \x01(\x05H\x01R\vPartitionID\x88\x01\x01B\f\n" +
	"\n" +
	"_TopicNameB\x0e\n" +
	"\f_PartitionID\"\x80\x01\n" +
	"\x16InitProducerIDResponse\x12*\n" +
	"\x03Ret\x18\x01 \x01(\x0e2\x13.broker_rpc.RetCodeH\x00R\x03Ret\x88\x01\x01\x12#\n" +
	"\n" +
	"ProducerID\x18\x02 \x01(\x04H\x01R\n" +
	"ProducerID\x88\x01\x01B\x06\n" +
	"\x04_RetB\r\n" +
	"\v_ProducerID*@\n" +
	"\aRetCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\r\n" +
	"\tNotLeader\x10\x01\x12\v\n" +
	"\aTimeOut\x10\x02\x12\f\n" +
	"\bErrOther\x10\x032\xbe\x03\n" +
	"\x06Broker\x12W\n" +
	"\fPushMessages\x12\x1f.broker_rpc.PushMessagesRequest\x1a .broker_rpc.PushMessagesResponse\"\x00(\x010\x01\x12S\n" +
	"\fPullMessages\x12\x1f.broker_rpc.PullMessagesRequest\x1a .broker_rpc.PullMessagesResponse\"\x00\x12P\n" +
	"\vCommitIndex\x12\x1e.broker_rpc.CommitIndexRequest\x1a\x1f.broker_rpc.CommitIndexResponse\"\x00\x12Y\n" +
	"\x0eGetCommitIndex\x12!.broker_rpc.GetCommitIndexRequest\x1a\".broker_rpc.GetCommitIndexResponse\"\x00\x12Y\n" +
	"\x0eInitProducerID\x12!.broker_rpc.InitProducerIDRequest\x1a\".broker_rpc.InitProducerIDResponse\"\x00B\x10Z\x0eapi/broker_rpcb\x06proto3"

var (
	file_api_broker_rpc_broker_rpc_proto_rawDescOnce sync.Once
	file_api_broker_rpc_broker_rpc_proto_rawDescData []byte
)

func file_api_broker_rpc_broker_rpc_proto_rawDescGZIP() []byte {
	file_api_broker_rpc_broker_rpc_proto_rawDescOnce.Do(func() {
		file_api_broker_rpc_broker_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_broker_rpc_broker_rpc_proto_rawDesc), len(file_api_broker_rpc_broker_rpc_proto_rawDesc)))
	})
	return file_api_broker_rpc_broker_rpc_proto_rawDescData
}

var file_api_broker_rpc_broker_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_broker_rpc_broker_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_broker_rpc_broker_rpc_proto_goTypes = []any{
	(RetCode)(0),                                                   // 0: broker_rpc.RetCode
	(*PushMessagesRequest)(nil),                                    // 1: broker_rpc.PushMessagesRequest
	(*PushMessagesResponse)(nil),                                   // 2: broker_rpc.PushMessagesResponse
	(*PullMessagesRequest)(nil),                                    // 3: broker_rpc.PullMessagesRequest
	(*PullMessagesResponse)(nil),                                   // 4: broker_rpc.PullMessagesResponse
	(*CommitIndexRequest)(nil),                                     // 5: broker_rpc.CommitIndexRequest
	(*CommitIndexResponse)(nil),                                    // 6: broker_rpc.CommitIndexResponse
	(*GetCommitIndexRequest)(nil),                                  // 7: broker_rpc.GetCommitIndexRequest
	(*GetCommitIndexResponse)(nil),                                 // 8: broker_rpc.GetCommitIndexResponse
	(*InitProducerIDRequest)(nil),                                  // 9: broker_rpc.InitProducerIDRequest
	(*InitProducerIDResponse)(nil),                                 // 10: broker_rpc.InitProducerIDResponse
	(*PushMessagesRequest_Topic)(nil),                              // 11: broker_rpc.PushMessagesRequest.Topic
	(*PushMessagesRequest_Topic_Partition)(nil),                    // 12: broker_rpc.PushMessagesRequest.Topic.Partition
	(*PushMessagesResponse_TopicResponses)(nil),                    // 13: broker_rpc.PushMessagesResponse.TopicResponses
	(*PushMessagesResponse_TopicResponses_PartitionResponses)(nil), // 14: broker_rpc.PushMessagesResponse.TopicResponses.PartitionResponses
	(*PullMessagesRequest_Topic)(nil),                              // 15: broker_rpc.PullMessagesRequest.Topic
	(*PullMessagesRequest_Topic_Partition)(nil),                    // 16: broker_rpc.PullMessagesRequest.Topic.Partition
	(*PullMessagesResponse_TopicResponses)(nil),                    // 17: broker_rpc.PullMessagesResponse.TopicResponses
	(*PullMessagesResponse_TopicResponses_PartitionResponses)(nil), // 18: broker_rpc.PullMessagesResponse.TopicResponses.PartitionResponses
}
var file_api_broker_rpc_broker_rpc_proto_depIdxs = []int32{
	11, // 0: broker_rpc.PushMessagesRequest.Topics:type_name -> broker_rpc.PushMessagesRequest.Topic
	13, // 1: broker_rpc.PushMessagesResponse.Topics:type_name -> broker_rpc.PushMessagesResponse.TopicResponses
	15, // 2: broker_rpc.PullMessagesRequest.Topics:type_name -> broker_rpc.PullMessagesRequest.Topic
	17, // 3: broker_rpc.PullMessagesResponse.Topics:type_name -> broker_rpc.PullMessagesResponse.TopicResponses
	0,  // 4: broker_rpc.CommitIndexResponse.Ret:type_name -> broker_rpc.RetCode
	0,  // 5: broker_rpc.GetCommitIndexResponse.Ret:type_name -> broker_rpc.RetCode
	0,  // 6: broker_rpc.InitProducerIDResponse.Ret:type_name -> broker_rpc.RetCode
	12, // 7: broker_rpc.PushMessagesRequest.Topic.Partitions:type_name -> broker_rpc.PushMessagesRequest.Topic.Partition
	14, // 8: broker_rpc.PushMessagesResponse.TopicResponses.Partitions:type_name -> broker_rpc.PushMessagesResponse.TopicResponses.PartitionResponses
	0,  // 9: broker_rpc.PushMessagesResponse.TopicResponses.PartitionResponses.Ret:type_name -> broker_rpc.RetCode
	16, // 10: broker_rpc.PullMessagesRequest.Topic.Partitions:type_name -> broker_rpc.PullMessagesRequest.Topic.Partition
	18, // 11: broker_rpc.PullMessagesResponse.TopicResponses.Partitions:type_name -> broker_rpc.PullMessagesResponse.TopicResponses.PartitionResponses
	0,  // 12: broker_rpc.PullMessagesResponse.TopicResponses.PartitionResponses.Ret:type_name -> broker_rpc.RetCode
	1,  // 13: broker_rpc.Broker.PushMessages:input_type -> broker_rpc.PushMessagesRequest
	3,  // 14: broker_rpc.Broker.PullMessages:input_type -> broker_rpc.PullMessagesRequest
	5,  // 15: broker_rpc.Broker.CommitIndex:input_type -> broker_rpc.CommitIndexRequest
	7,  // 16: broker_rpc.Broker.GetCommitIndex:input_type -> broker_rpc.GetCommitIndexRequest
	9,  // 17: broker_rpc.Broker.InitProducerID:input_type -> broker_rpc.InitProducerIDRequest
	2,  // 18: broker_rpc.Broker.PushMessages:output_type -> broker_rpc.PushMessagesResponse
	4,  // 19: broker_rpc.Broker.PullMessages:output_type -> broker_rpc.PullMessagesResponse
	6,  // 20: broker_rpc.Broker.CommitIndex:output_type -> broker_rpc.CommitIndexResponse
	8,  // 21: broker_rpc.Broker.GetCommitIndex:output_type -> broker_rpc.GetCommitIndexResponse
	10, // 22: broker_rpc.Broker.InitProducerID:output_type -> broker_rpc.InitProducerIDResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_broker_rpc_broker_rpc_proto_init() }
func file_api_broker_rpc_broker_rpc_proto_init() {
	if File_api_broker_rpc_broker_rpc_proto != nil {
		return
	}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[16].OneofWrappers = []any{}
	file_api_broker_rpc_broker_rpc_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_broker_rpc_broker_rpc_proto_rawDesc), len(file_api_broker_rpc_broker_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_broker_rpc_broker_rpc_proto_goTypes,
		DependencyIndexes: file_api_broker_rpc_broker_rpc_proto_depIdxs,
		EnumInfos:         file_api_broker_rpc_broker_rpc_proto_enumTypes,
		MessageInfos:      file_api_broker_rpc_broker_rpc_proto_msgTypes,
	}.Build()
	File_api_broker_rpc_broker_rpc_proto = out.File
	file_api_broker_rpc_broker_rpc_proto_goTypes = nil
	file_api_broker_rpc_broker_rpc_proto_depIdxs = nil
}
