// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: api/registry_info/registry_info.proto

package registry_info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartitionStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LeaderAddress   *string                `protobuf:"bytes,1,opt,name=LeaderAddress,proto3,oneof" json:"LeaderAddress,omitempty"`
	FollowerAddress []string               `protobuf:"bytes,2,rep,name=FollowerAddress,proto3" json:"FollowerAddress,omitempty"`
	Version         *uint64                `protobuf:"varint,3,opt,name=Version,proto3,oneof" json:"Version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartitionStatus) Reset() {
	*x = PartitionStatus{}
	mi := &file_api_registry_info_registry_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionStatus) ProtoMessage() {}

func (x *PartitionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_info_registry_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionStatus.ProtoReflect.Descriptor instead.
func (*PartitionStatus) Descriptor() ([]byte, []int) {
	return file_api_registry_info_registry_info_proto_rawDescGZIP(), []int{0}
}

func (x *PartitionStatus) GetLeaderAddress() string {
	if x != nil && x.LeaderAddress != nil {
		return *x.LeaderAddress
	}
	return ""
}

func (x *PartitionStatus) GetFollowerAddress() []string {
	if x != nil {
		return x.FollowerAddress
	}
	return nil
}

func (x *PartitionStatus) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type SubList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubTopics     []string               `protobuf:"bytes,1,rep,name=SubTopics,proto3" json:"SubTopics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubList) Reset() {
	*x = SubList{}
	mi := &file_api_registry_info_registry_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubList) ProtoMessage() {}

func (x *SubList) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_info_registry_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubList.ProtoReflect.Descriptor instead.
func (*SubList) Descriptor() ([]byte, []int) {
	return file_api_registry_info_registry_info_proto_rawDescGZIP(), []int{1}
}

func (x *SubList) GetSubTopics() []string {
	if x != nil {
		return x.SubTopics
	}
	return nil
}

var File_api_registry_info_registry_info_proto protoreflect.FileDescriptor

var file_api_registry_info_registry_info_proto_rawDesc = string([]byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x0d, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1d, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x48, 0x01, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x10,
	0x0a, 0x0e, 0x5f, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x07,
	0x53, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x53, 0x75, 0x62, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_api_registry_info_registry_info_proto_rawDescOnce sync.Once
	file_api_registry_info_registry_info_proto_rawDescData []byte
)

func file_api_registry_info_registry_info_proto_rawDescGZIP() []byte {
	file_api_registry_info_registry_info_proto_rawDescOnce.Do(func() {
		file_api_registry_info_registry_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_registry_info_registry_info_proto_rawDesc), len(file_api_registry_info_registry_info_proto_rawDesc)))
	})
	return file_api_registry_info_registry_info_proto_rawDescData
}

var file_api_registry_info_registry_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_registry_info_registry_info_proto_goTypes = []any{
	(*PartitionStatus)(nil), // 0: registry_info.PartitionStatus
	(*SubList)(nil),         // 1: registry_info.SubList
}
var file_api_registry_info_registry_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_registry_info_registry_info_proto_init() }
func file_api_registry_info_registry_info_proto_init() {
	if File_api_registry_info_registry_info_proto != nil {
		return
	}
	file_api_registry_info_registry_info_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_registry_info_registry_info_proto_rawDesc), len(file_api_registry_info_registry_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_registry_info_registry_info_proto_goTypes,
		DependencyIndexes: file_api_registry_info_registry_info_proto_depIdxs,
		MessageInfos:      file_api_registry_info_registry_info_proto_msgTypes,
	}.Build()
	File_api_registry_info_registry_info_proto = out.File
	file_api_registry_info_registry_info_proto_goTypes = nil
	file_api_registry_info_registry_info_proto_depIdxs = nil
}
